# Generated by Django 4.0.5 on 2022-06-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название договора')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='№')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Сумма договора (без НДС)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('sum_incorrect', models.BooleanField(blank=True, default=False, null=True, verbose_name='Сумма договора не соответствует сумме по этапам')),
                ('is_plan', models.BooleanField(blank=True, default=False, null=True, verbose_name='Это плановый договор')),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Это закрытый договор')),
                ('is_border_contract', models.BooleanField(blank=True, default=False, null=True, verbose_name='Это рамочный договор')),
                ('sum_with_nds', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Сумма договора (c НДС)')),
                ('be_nds', models.BooleanField(blank=True, default=False, null=True, verbose_name='+НДС')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('counterparty__name', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование контрагента')),
                ('tin', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('iec', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='PaymentStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название этапа оплаты по договору')),
                ('date', models.DateField(verbose_name='Дата оплаты этапа')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Сумма оплаты этапа (без НДС)')),
                ('sum_with_nds', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Сумма договора (c НДС)')),
                ('be_nds', models.BooleanField(blank=True, default=False, null=True, verbose_name='+НДС')),
                ('paymented', models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплачено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Этап оплаты по договору',
                'verbose_name_plural': 'Этапы оплаты по договорам',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='№ платежного поручения')),
                ('date', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Сумма оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('sum_with_nds', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Сумма договора (c НДС)')),
                ('be_nds', models.BooleanField(blank=True, default=False, null=True, verbose_name='+НДС')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty', verbose_name='Контрагент')),
                ('payment_stages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.paymentstages', verbose_name='Этап оплаты по договору')),
            ],
            options={
                'verbose_name': 'Оплата по договору',
                'verbose_name_plural': 'Оплаты по договорам',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.counterparty', verbose_name='Контрагент'),
        ),
    ]
